### PR TITLE
Support react 18

### PR DESCRIPTION
**Pull request by rkulinski**

### CODE REVIEW

**Comment by aboveyunhai** [comment]
@rkulinski  any release plan to make this version available, rc or beta or whatever tag with it?

**Comment by nikolai-vysotskyi** [comment]
anyone else here? very topical 🤔

**Comment by RonaldR** [comment]
Hi @rkulinski is this project still alive? Would really like to see a new release with these changes.
(cc @tannerlinsley)

**Comment by tannerlinsley** [comment]
Yes it is. And it will soon!

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @tannerlinsley, Can you please release this on npm? 🤞

**Pull request merged**
